name: workflow.yml

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
          cache: maven

      - name: Build project
        run: ./mvnw --batch-mode --update-snapshots package -DskipTests -P full

      - name: Archive maven repo
        run: tar -czf m2-repository.tar.gz ~/.m2/repository

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: start-site/target/start-site-exec.jar

      - name: Upload maven cache
        uses: actions/upload-artifact@v4
        with:
          name: m2-cache
          path: m2-repository.tar.gz



