name: workflow.yml

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build project
        run: ./mvnw clean install -DskipTests=true -Dmaven.test.skip=true -P full

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: start-site/target/*exec.jar
